import Link from "next/link";
import { ArrowRight, FileText, PenLine } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { getMyPost } from "../_action/my-post";

export default async function AuthorDashboard() {
  const result = await getMyPost();
  const posts = Array.isArray(result) ? result : [];
  return <div className="flex flex-col gap-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold uppercase tracking-[.16em] text-primary">Studio</p><h1 className="mt-2 text-4xl font-semibold tracking-[-.04em]">Author dashboard</h1><p className="mt-2 text-muted-foreground">Manage your publishing work from one focused space.</p></div><Button asChild><Link href="/create-post"><PenLine data-icon="inline-start" /> New post</Link></Button></div><div className="grid gap-4 sm:grid-cols-2"><Card><CardContent className="flex items-center gap-4 p-6"><FileText className="size-5 text-primary" /><div><p className="text-2xl font-semibold">{posts.length}</p><p className="text-sm text-muted-foreground">Posts returned by your account</p></div></CardContent></Card><Card><CardContent className="p-6"><p className="text-sm text-muted-foreground">Publishing status</p><p className="mt-2 font-medium">{posts.length ? "Your work is ready to manage." : "No posts yet"}</p></CardContent></Card></div><Card><CardHeader><CardTitle>My posts</CardTitle></CardHeader><CardContent>{posts.length ? <div className="divide-y divide-border">{posts.map((post: { id: string; title: string; status?: string; createdAt?: string }) => <div key={post.id} className="flex items-center justify-between gap-4 py-4"><div className="min-w-0"><p className="truncate font-medium">{post.title}</p><p className="mt-1 text-xs text-muted-foreground">{post.createdAt ? new Date(post.createdAt).toLocaleDateString() : ""}</p></div><div className="flex items-center gap-3"><Badge variant="secondary">{post.status ?? "Published"}</Badge><Button asChild variant="ghost" size="icon" aria-label={`Edit ${post.title}`}><Link href={`/edit-post/${post.id}`}><ArrowRight /></Link></Button></div></div>)}</div> : <div className="rounded-xl border border-dashed border-border p-10 text-center text-muted-foreground">No posts yet. Create your first story when you are ready.</div>}</CardContent></Card></div>;
}
